spring:
  application:
    name: Video Streaming Mono

  datasource:
    url: jdbc:mysql://localhost:3306/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASS}

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect

  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB

  threads:
    virtual:
      enabled: true

thumbnail:
  default-local-directory: "./thumbnails"

video:
  default-local-directory: "./videos"
  default-local-hls-directory: "./videos-hls"

jwt:
  secret: ${JWT_SECRET}
  expirationTime: 7200000

cors:
  allowed-origins: "http://localhost:3000/"
  allow-credentials: false